Add saml docs
reportportal/documentation pull request #387
Opened 2022-06-08 12:11 UTC by pressayuliya

2022-06-08 13:38 UTC, AmsterGet requested changes
Here we've added separate Plugins section to the docs structure.
Is it make sense to hold all plugins related docs under such section before publishing it to the prod?
@alena-babrova what do you think?

2022-06-08 13:38 UTC, AmsterGet commented on src/md/pages/documentation.hbs
> +    'src/computeds/md/src/Plugins/AzureSAMLIntegration.md'
Please add trailing comma at the end of line.

2022-06-08 13:38 UTC, AmsterGet commented on src/md/pages/documentation.hbs
> +    'src/computeds/md/src/Plugins/AzureSAMLIntegration.md'
Are you sure this section should be at the top of the documentation?

2022-06-08 14:19 UTC, alena-babrova commented
> Here we've added separate Plugins section to the docs structure.
> Is it make sense to hold all plugins related docs under such section before publishing it to the prod?
> @alena-babrova what do you think?

Yes, I agree with you @AmsterGet.
I think Plugins section should include all plugins documentation.
We already have plugins documentation in another place.

![image](https://user-images.githubusercontent.com/89584140/172639670-e84cf61c-c4eb-42f3-9820-5ea5b18752d8.png)

2022-06-10 15:28 UTC, AmsterGet commented on src/md/pages/documentation.hbs
> +    'src/computeds/md/src/Plugins/AzureSAMLIntegration.md'
Decided to leave integrations documentation in the current section for now.
Discussion scheduled.

2022-06-10 15:29 UTC, merged